version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_EXTENSION_XDEBUG: 1
      XDEBUG_CONFIG: 'remote_host=192.168.100.101 remote_enable=1 profiler_enable=0'
      PHP_IDE_CONFIG: "serverName=Docker"
    command: ["php", "./examples/main.php"]
    user: ${CURRENT_UID}
    volumes:
      - ./:/app
    networks:
      - yahooauc-net

networks:
  yahooauc-net:
    name: yahooauc-net
